### ISSUE TITLE
Restream.io control panel control

### ISSUE THREAD

**Issue by frankleggett** [bitfocus/companion-module-restream-api#1]
I am looking for a module that can control the Restream.io dashboard so I can turn on and turn off channels with a streamdeck button. There is a restream api but it is beyond my abiltiy to do this.

**Comment by BenJamesAndo** [comment]
Noob question, but how do I test it out? Is there a build for Windows with it included?

**Comment by josephdadams** [comment]
@QuinnMatthews are you ready for this module to be included in the companion v3 beta builds?

**Comment by QuinnMatthews** [comment]
@josephdadams I believe it could be included in a beta build. I would still like to finish up the last features sometime soon, just haven't had as much time on my plate to get around to it.

**Comment by josephdadams** [comment]
I included it in the betas, it should make its way into builds within 6 hours.

**Comment by BenJamesAndo** [comment]
Tested it now. Works perfectly on one computer and on another it works for one key press and then I get `Instance/ModuleHost: Instance "restream" failed to init: Error: Call timed out Error: Call timed out`. Both Windows 11 running the same & latest versions of the beta.
Fortunately it works on the production computer so I can get by with it.

If I can I'd like to add another request to the list of actions. The ability to select the next upcoming event stream for channels such as YouTube. Stream key variable is great and I'd likely use that, but the ability to force Restream to select the next event would be handy. Cos once you've finished a YouTube Event in Restream it defaults to creating a new event next time you go live, instead of selecting the next upcoming event.

Or another option would be to have a Custom RTMP channel in Restream and have an action to change the RTMP URL and Stream key that could be gotten via the variable.

**Comment by QuinnMatthews** [comment]
Hey @BenJamesAndo, are you using the same restream application for both? I'm not sure why that might be happening. After it happens are the Access token and refresh token still populated in the config? I know that some errors will clear those config items. 

As far as the new action for YouTube, I don't think restream has any documented API endpoint that can be used to make that change. Changing the custom RTMP URL *might* be possible if restream includes that as part of the "channel meta" endpoint but I'd have to check.

**Comment by QuinnMatthews** [comment]
@BenJamesAndo Thanks for that additional info, can you include the full logs including all of Console, info, warning, and error. You should be able to get these specifically for the restream module by clicking the log icon next to the module: 
![image](https://user-images.githubusercontent.com/55562296/216503041-2b6b6b0b-b039-4618-9ec2-ea2207f14839.png)
This should include more verbose output that shows exactly what is happening behind the scenes. Hopefully something like this:
![image](https://user-images.githubusercontent.com/55562296/216504215-d5141088-ccde-46fe-a1ff-226e50184980.png)
(You do have to have the logging page open when the error occurs) 

**Please remove any sensitive items from the log, when certain errors occur, the entire request is logged, and it could include details such as your access token and refresh token**

Regarding your feedback regarding feedback, I do trigger a manual poll of the feedbacks and variables following a channel update however it just calls the normal `poll()` function which polls the information and status of all the channels in your restream account which means that it could take a few seconds to complete depending on the number of channels you have. I could look into refactoring and optimizing this to just poll information regarding the specific channels, I just never noticed it to be an issue, but it could be because I only have 5 channels defined. (Currently the scheduled poll happens every 30 seconds, though I do have plans to make this configurable value)


Thanks for your help with troubleshooting this, hopefully we will be able to get to the bottom of it.

**Comment by BenJamesAndo** [comment]
@QuinnMatthews attached is the log file.
[Restream Companion error.log](https://github.com/bitfocus/companion-module-restream-api/files/10575350/Restream.Companion.error.log)

Yeah updating the feedback to be quicker is purely for added confidence that it worked. But in it's current state it's definitely useable.

**Comment by QuinnMatthews** [comment]
Thanks @BenJamesAndo  I'll take a look through it, I did go ahead and remove it from your comment because it included your restream client id and secret which is also sensitive information, it won't give access to your account, but it could allow someone else to abuse the API posing as you. You might want to consider removing your existing restream app and recreating a new one.

**Comment by QuinnMatthews** [comment]
@BenJamesAndo  This seems to be the important part of the error in the log you provided:

```
TypeError: this.getPlatforms is not a function
    at Timeout.poll [as _onTimeout] (C:\Program Files\Companion\resources\bundled-modules\restream-api\main.js:2:5017)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

which could be an issue with how `this` is being bound to the automatic poll... I'll definitely want to look into this more, this whole thing is a little outside my area of expertise, but I should be able to compare to other modules...
That said, this sort of error shouldn't clear your access code or refresh code and it seemed like the module was functioning after it restarted which (while a crash is certainly not good) means that it should recover on its own. Can you confirm that it did begin working again? I know you mentioned the two codes being cleared, did that happen in this case? Just want to make sure there aren't 2 separate issues that I need to be looking for.  

```
TypeError: this.getPlatforms is not a function
    at Timeout.poll [as _onTimeout] (C:\Program Files\Companion\resources\bundled-modules\restream-api\main.js:2:5017)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.12.1
Updating Feedbacks
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: 
Sentry disabled
Module-host accepted registration
Checking Configuration
Checking Authentication Status
Making test request to restream api
Test request successful
info: Successfully connected to Restream
```

**Comment by BenJamesAndo** [comment]
@QuinnMatthews In this particular case the access codes don't clear. Although I can't even check them. I think that only happened once when I was first adding it in. So probably is something completely separate and may have been human error on my end.
This current issue does in fact try to recover itself but it alternates mostly between crashed and initializing.
![image](https://user-images.githubusercontent.com/44917135/216512028-e02d9726-d2ee-480c-9628-8d8f8f64a5e0.png)
![image](https://user-images.githubusercontent.com/44917135/216512034-bcab1d52-c591-498e-b262-3acb3a92fc8e.png)

**Comment by QuinnMatthews** [comment]
That would make sense if that has only happened once, there is only a very specific circumstance that leads to those being cleared and wouldn't seem to be related to this issue. 
How interesting though on the crash loop, I've never run into that before and it doesn't seem to be logging any issues before it crashes again but I do see it now in the logs where it stops and restarts randomly... it always seems to be during the poll, it could be the way that I try to speed up some of the calls by making them asynchronously, I think I see a potential bug in that code. I probably can't resolve it tonight, but I should have time to look into it fairly soon (please feel free to bug me if I don't)

**Comment by mrcheap1984** [comment]
Hi @QuinnMatthews 

I have written a php with the api to restream.io program before, and am interested in this module.

I'm trying to setup the connection, I follow the instructions in terms of logging in, but companion did not populate the access and refresh tokens, after the authentication and redirection back to companion.

Due to my past experience I decided to put in the refresh and access tokens manually in, but unfortunately it goes into a crash loop.  Extract below.

Operating System: Ubuntu 22.04
Docker Version:  24.0.2, build cb74dfc
Companion Version: v3.0.0-rc1

```
system: ** Log cleared **
system: ** Connection started **
Starting up module class: 
Sentry disabled
Module-host accepted registration
Checking Configuration
Checking Authentication Status
Making test request to restream api
Test request successful
Polling APIs
info: Successfully connected to Restream
Getting Platforms
Getting Channels
Getting Channel Meta
Getting Channel Meta
{
  error: {
    name: 'UnknownError',
    code: 500,
    status: 500,
    statusCode: 500,
    message: 'Unknown server error'
  }
}
500
Ee [AxiosHeaders] {
  date: 'Thu, 01 Jun 2023 07:36:22 GMT',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '107',
  connection: 'close',
  etag: 'W/"6b-PmFGw6M73roJjKPdtP5Ux8EJ4UU"',
  'strict-transport-security': 'max-age=15552000; includeSubDomains',
  vary: 'Origin',
  'x-content-type-options': 'nosniff',
  'x-dns-prefetch-control': 'off',
  'x-download-options': 'noopen',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  'cf-cache-status': 'DYNAMIC',
  server: 'cloudflare',
  'cf-ray': '7d05c8fc9bf7aafc-SYD'
}
error: Bad Response from Restream API - 500
error: Failed to init: Error: Cannot read properties of undefined (reading 'data') TypeError: Cannot read properties of undefined (reading 'data')
    at t.InstanceBase.apiWrapper (/app/bundled-modules/restream-api/main.js:2:9971)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.InstanceBase.getChannelMeta (/app/bundled-modules/restream-api/main.js:2:6827)
    at async /app/bundled-modules/restream-api/main.js:2:5125
    at async Promise.all (index 0)
    at async t.InstanceBase.poll (/app/bundled-modules/restream-api/main.js:2:5071)
    at async t.InstanceBase.init (/app/bundled-modules/restream-api/main.js:2:3313)
    at async /app/bundled-modules/restream-api/main.js:2:228580
    at async /app/bundled-modules/restream-api/main.js:2:206658
error: Trace: Init failed: TypeError: Cannot read properties of undefined (reading 'data')
    at /app/bundled-modules/restream-api/main.js:2:228649
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/bundled-modules/restream-api/main.js:2:206658
system: ** Connection stopped **
system: ** Connection started **
```

**Comment by QuinnMatthews** [comment]
Hi @mrcheap1984, Sorry about this issue. I'm not sure why the authentication/refresh tokens didn't automatically populate. Unfortunately, that area is a little buggy because there isn't a great way to handle the whole OAUTH flow within Companion, but that is why I made the fields able to be manually populated. 

In terms of the crash loop, can I ask what restream channel platforms you have on your account? It looks like it is successfully connecting to restream but then failing to retrieve one or more channels metadata (see Restream doc [here](https://developers.restream.io/docs#channel-meta) for API endpoint).

**Comment by QuinnMatthews** [comment]
Hey, @mrcheap1984 I actually went to use this module tonight and ran into the same problem. It looks like that endpoint is broken on restream's end because I get a 500 error just running some test requests in postman. Unfortunately, that's not an easy endpoint to leave out because it's what populates the channel title variable. I might reach out to restream support tomorrow to see if they have any ideas.

**Comment by mrcheap1984** [comment]
@QuinnMatthews, I've got Facebook (37) and YouTube Events (5) enabled.  ID start with 617xxxx
I tried disabling those outputs but the error persists.
In term of characters titles and descriptions, just alpha numeric, there do have the ":" and "-" characters.

**Comment by QuinnMatthews** [comment]
Yeah it still will call the meta endpoint regardless of if it's enabled or disabled. My guess (though I haven't tested this nor am suggesting that you test it) would be that the module would work only if all channels/outputs were fully removed from the account because then it wouldn't try to hit any of the meta endpoints. Unfortunately, we are pretty much at the mercy of restream at the moment,

**Comment by khazdan37** [comment]
I just so happen to be trying to setup this module a couple of days ago, confused when it didn't work until I found the recent issues here. I don't know if anyone was monitoring, but yesterday I tried the module again and it worked. I did have to setup the module on a local instance of companion and then copy those tokens to my actual companion, and the tokens seemed to disappear overnight, but the crash loop is gone. I popped the tokens back in and we were good to go again.

**Comment by QuinnMatthews** [comment]
That's great that it's working now - restream must have fixed the issue. Thanks for updating us @khazdan37. 
Unfortunately, I still haven't found a great way to handle the OAUTH flow on a remote device. If anyone has any suggestions, please let me know. 

@mrcheap1984 Have you been able to get your instance working?

For organizational purposes, I've created a new GitHub issue addressing the OAUTH flow issue #4

**Comment by frankleggett** [comment]
Hi,

I have followed the video and I get a green tick but as soon as I go to set this to a button the connection crashes.

I have attached the log.
[module-log-06_12_2023-13 12 04.csv](https://github.com/bitfocus/companion-module-restream-api/files/13583265/module-log-06_12_2023-13.12.04.csv)

**Comment by frankleggett** [comment]
Hi QuinnMatthews, firstly thanks for all the work on the module. I though can't get it to work. I have followed the usefull video on Youtube by Geert https://www.youtube.com/watch?v=h3ul0mrtDjY. When I click OK on Restream to allow I get the green tick in companion but as soon as I try to configure a button the module crashes. I have attached the error log.
[module-log-06_12_2023-13 12 04.csv](https://github.com/bitfocus/companion-module-restream-api/files/13583350/module-log-06_12_2023-13.12.04.csv)
I have tried this on 2 different computers one has Windows 10 and one has Windows 11. Both are using Companion 3.1.2

**Comment by heebee-eldee** [comment]
@QuinnMatthews Hello! I have found this module very useful for turning channels off and on, however I am really hoping that there is a way to 'Change the stream titles'. Is this something that you are still working on by any chance please?
